version: '3.9'
services:
  blog_deepak: 
    build: 
      context: ./mynote_client
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    command: dev 
    volumes:
        - ./mynote_client:/usr/src/app
        - /usr/src/app/node_modules
        - /usr/src/app/.nextgit 