FROM node:16.13.2-alpine3.14

WORKDIR /app

COPY package*.json ./

RUN npm i

COPY . .

RUN npm run build

RUN addgroup -g 1001 -S nodejs
RUN adduser -S nextjs -u 1001

EXPOSE 3000

CMD ["npm", "run", "dev"]